# Generated by Django 4.2.14 on 2024-09-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
